name: 🐞 Bug report
description: Report an issue
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link via StackBlitz [vite with script setup](https://stackblitz.com/github/bootstrap-vue-next/bootstrap-vue-next/tree/main/templates/vite?file=src%2Fcomponents%2FComp.vue,src%2FApp.vue) / [light vue](https://stackblitz.com/fork/bootstra-vue-next-template?file=src%2Fcomponents%2FComp.vue,src%2FApp.vue) or a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required.
      placeholder: Reproduction
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - pnpm
        - bun
        - yarn
        - npm
        - n/a
    validations:
      required: true
