name: 🐞 Compatibility report
description: Create a report on missing features from Bootstrap v5 or BootstrapVue v2
labels: [compatibility enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this compatibility report!
  - type: dropdown
    id: feature-type
    attributes:
      label: Missing feature is from
      description: "Please source of the feature: Bootstrap-vue or Bootstrap v5."
      options:
        - bootstrap-vue
        - Bootstrap v5
    validations:
      required: true
  - type: input
    id: docs
    attributes:
      label: Docs
      description: Please provide a link to the Bootstrap-vue docs or the most current version of the Bootstrap v5 docs for this feature.
      placeholder: link
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the missing feature
      description: A clear and concise description of what is missing. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Feature description
    validations:
      required: true
