export {default as toastPlugin} from './toastPlugin'
export {default as breadcrumbPlugin} from './breadcrumbPlugin'
export {default as idPlugin} from './idPlugin'
export {default as modalControllerPlugin} from './modalControllerPlugin'
export {default as modalManagerPlugin} from './modalManagerPlugin'
export {default as rtlPlugin} from './rtlPlugin'
export {default as defaultsPlugin} from './defaultsPlugin'
