# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: npm-publish-debug

on:
  push:
  branches:
    - ci/debug

jobs:
  publish-npm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Build library
        run: pnpm run build

      - name: Test library
        run: pnpm test

      - name: Git status
        run: git status

      - name: Publish
        run: pnpm publish --filter bootstrap-vue-3 --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
